#!/bin/bash
# scrot -> pomf.se, by @__akiaki
 
# take the shot
FILE="`scrot $@ -e 'echo -n $f'`"
 
# upload it and grab the URL
BASE=""; TRY=0
while [ "x$BASE" == "x" ] && [ $TRY -lt 3 ]; do
TRY=$[$TRY + 1]
echo "Uploading... (try $TRY)"
JSON="`curl -sf -F "files[]=@$FILE" http://pomf.se/upload.php`"
BASE="`echo "$JSON" | python -c "from __future__ import print_function;print(__import__('json').loads(__import__('sys').stdin.read())['files'][0]['url'])" 2>/dev/null`"
done
 
if [ $TRY -eq 3 ]; then
echo "Giving up."
exit 1
fi
 
URL="http://a.pomf.se/$BASE"
 
# copy the URL to the clipboard
which xclip 2>&1 >/dev/null && XCLIP=1
if [ $XCLIP == 1 ]; then
echo -n "$URL" | xclip -selection clipboard
echo "$URL (has been copied to clipboard)"
else
echo "$URL"
fi
